### ISSUE TITLE
Call to undefined function get_post_type_archive_template()

### ISSUE THREAD

**Issue by alexlino** [keesiemeijer/custom-post-type-date-archives#2]
Hi, I was trying to use the plugin. The monthly archive list shows ok, but when I click a month, I got this message:  Fatal error: Call to undefined function get_post_type_archive_template() in D:\Programas\wamp\www\carusojrea\wp-content\plugins\custom-post-type-date-archives\includes\install.php 

Searching the code for get_post_type_archive_template() function shows zero results.

Can you help me?

Thanks

**Comment by keesiemeijer** [comment]
Hi,
That's a WordPress function.
https://developer.wordpress.org/reference/functions/get_post_type_archive_template/

What version of WordPress are you using?

**Comment by alexlino** [comment]
Oh yes, this site is very old (3.6), can´t update because is very plugin dependent. That´s why it didn´t work for me. But thanks, I commented the line that calls the function, worked fine. All i have to do is create an archieve.php template and is done. Rewrite rules saved my life.

Thanks!

**Comment by keesiemeijer** [comment]
The plugin requires at least WordPress 3.9

I'm glad you solved your issue
